name: Between a rock and a crazy place
url: //blog.merovius.de/
future: true

markdown: redcarpet
highlighter: pygments
gems: ['jekyll-gist']

encoding: UTF-8

sitemap:
    url: https://blog.merovius.de
    exclude:
        - 'atom.xml'
        - 'impressum.html'
        - 'google59e5fe5f31947a20.html'
        - 'robots.txt'

redcarpet:
    extensions: ["with_toc_data"]
